### ISSUE TITLE
Add an ability to apply all the rules

### ISSUE THREAD

**Issue by vyshkant** [buzinas/tslint-eslint-rules#304] opened 2018-02-28 18:38 UTC
# The problem

I had a problem with applying the rules providing by this package, and I think I have an idea how can it be improved.

Suppose, I have the next TSLint config:
```json
{
  "extends": [
    "tslint:all",
    "tslint-eslint-rules",
  ]
}
```
This configuration means, that all the rules of preset `tslint:all` will be applied to my code. So I expect, that adding `tslint-eslint-rules` to `extends` section will do the same: the rules of `tslint-eslint-rules` preset will be applied to my code.

To my surprise, it isn't so. I spent about an hour to understand, why do I see next message:

```bash
$ node node_modules/tslint/bin/tslint --project .tsrc --config .tslint.json
No valid rules have been specified
Done in 1.38s.
```

And in the end, I had copied the content of https://github.com/buzinas/tslint-eslint-rules/blob/master/eslint_tslint.json into the config of my project and it worked.

# Suggestion

I suggest to create a preset like `tslint-eslint-rules:all`, so that its use in the `extends` section led to the applying of all the rules provided by this package.

**Comment by buzinas** [comment] 2018-02-28 20:06
Thanks for the suggestion! Though, we don't want to be opinionated about which rules you should be using. We do have a `json` file in the repo that we use to linter our own project, which is opinionated.

Dupe of #229 (and others).

**Comment by buzinas** [comment] 2018-02-28 20:08
Thanks for the suggestion! Though, we don't want to be opinionated about which rules you should be using. We do have a `json` file in the repo that we use to linter our own project, which is opinionated.

**Closed by buzinas** 2018-02-28 20:08 UTC
Labels: suggestion
